version: '3.9'

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE_NAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend:
    build:
      context: .
    environment:
      - DB_HOST=pg         # указываем на имя сервиса PostgreSQL
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=1234
      - DB_NAME=postgres
    depends_on:
      - pg
    ports:
      - "8080:8080"